### PR TITLE
Change project layout

### PR DESCRIPTION
**Pull request by renanivo**
I was thinking about how to create a package for this project and deploy to production without having to edit the `settings.py` file in place. So I took a look at how open source django projects do that ([here](https://code.djangoproject.com/wiki/DjangoResources#Open-SourceDjangoprojects) and [here](https://github.com/rosarior/awesome-django#projects)).

Usually, they just provide apps to be installed via `pip` and leverage for the user to create a django project with settings.

This pull request adds the "production" requirements to setup.py and move django project files to an `example` folder. So that we can have a sample project to develop and test our apps.

### CODE REVIEW

**Comment by drgarcia1986** [comment]
Hum, I'm not sure about this, you look [sentry](https://github.com/getsentry/sentry) before make this decision?

**Comment by renanivo** [comment]
Okay, sentry seems to have figured out a way to have an easy setup using an approach different from the majority. I will take a couple days to install sentry and understand how it works under the hood.

**Comment by drgarcia1986** [comment]
I'm installed sentry once and I'm think it's very easy to use, just install sentry from pip and run `sentry --config={{ sentry_config_path }} start http`. This config file is a simple django settings file.

**Comment by renanivo** [comment]
I just set up sentry and took a very deep look at its code. I think there are very good ideas we can bring to houserules (like the idea of default project configs in `sentry.conf` module), but _sentry_ also has some code that, even though they facilitate the developer's experience, would be an overhead to a MVP (like the command line interface to manage its configurations and handle the `manage.py` commands).

We could get there sometime in the future and have a _sentry-like_ setup, but right now I think it is better to _stand in the shoulder of giants_ and avoid the overhead of creating interfaces over django's interfaces.

What do you think? Did I miss something?

**Comment by drgarcia1986** [comment]
rebase + :+1: = :tada:

**Pull request merged**
